copy schools_master(year, district , block , cluster , school_id, school_name , moi , math_minimum_or_above_percentage , kannada_minimum_or_above_percentage , clas , total_students , math_above_average , math_average , math_minimum , math_below_minimum , kannada_above_average , kannada_average , kannada_minimum , kannada_below_minimum) from '/home/brijesh/sikshana_report/report/sql/sikshana_assessment_2011-12.csv' with csv;

copy schools_master(year, district , block , cluster , school_id, school_name , moi , math_minimum_or_above_percentage , kannada_minimum_or_above_percentage , clas , total_students , math_above_average , math_average , math_minimum , math_below_minimum , kannada_above_average , kannada_average , kannada_minimum , kannada_below_minimum) from '/home/brijesh/sikshana_report/report/sql/sikshana_assessment_2012-13.csv' with csv;

copy schools_master(year, district , block , cluster , school_id, school_name , moi , math_minimum_or_above_percentage , kannada_minimum_or_above_percentage , clas , total_students , math_above_average , math_average , math_minimum , math_below_minimum , kannada_above_average , kannada_average , kannada_minimum , kannada_below_minimum) from '/home/brijesh/sikshana_report/report/sql/sikshana_assessment_2013-14_baseline.csv' with csv;
update schools_master set year=trim(year), district=trim(district), block=trim(block), cluster=trim(cluster), school_name=trim(school_name), moi=trim(moi);
	
insert into district_aggregation(year, name, clas, math_above_average, math_average, math_minimum, math_below_minimum, kannada_above_average, kannada_average, kannada_minimum, kannada_below_minimum, total) select distinct year, district, clas, sum(math_above_average), sum(math_average), sum(math_minimum), sum(math_below_minimum), sum(kannada_above_average), sum(kannada_average), sum(kannada_minimum), sum(kannada_below_minimum), (sum(math_above_average) + sum(math_average) + sum(math_minimum) + sum(math_below_minimum))
from schools_master group by year, district, clas;

insert into block_aggregation(year, name, clas, math_above_average, math_average, math_minimum, math_below_minimum, kannada_above_average, kannada_average, kannada_minimum, kannada_below_minimum, total) select distinct year, block, clas, sum(math_above_average), sum(math_average), sum(math_minimum), sum(math_below_minimum), sum(kannada_above_average), sum(kannada_average), sum(kannada_minimum), sum(kannada_below_minimum), (sum(math_above_average) + sum(math_average) + sum(math_minimum) + sum(math_below_minimum))
from schools_master group by year, block, clas;

insert into cluster_aggregation(year, name, clas, math_above_average, math_average, math_minimum, math_below_minimum, kannada_above_average, kannada_average, kannada_minimum, kannada_below_minimum, total) select distinct year, cluster, clas, sum(math_above_average), sum(math_average), sum(math_minimum), sum(math_below_minimum), sum(kannada_above_average), sum(kannada_average), sum(kannada_minimum), sum(kannada_below_minimum), (sum(math_above_average) + sum(math_average) + sum(math_minimum) + sum(math_below_minimum))
from schools_master group by year, cluster, clas;

insert into school_aggregation(year, name, clas, math_above_average, math_average, math_minimum, math_below_minimum, kannada_above_average, kannada_average, kannada_minimum, kannada_below_minimum, total) select distinct year, school_name, clas, sum(math_above_average), sum(math_average), sum(math_minimum), sum(math_below_minimum), sum(kannada_above_average), sum(kannada_average), sum(kannada_minimum), sum(kannada_below_minimum), (sum(math_above_average) + sum(math_average) + sum(math_minimum) + sum(math_below_minimum))
from schools_master group by year, school_name, clas;

insert into state_aggregation(year, name, clas, math_above_average, math_average, math_minimum, math_below_minimum, kannada_above_average, kannada_average, kannada_minimum, kannada_below_minimum, total) select distinct year, 'all' as name, clas, sum(math_above_average), sum(math_average), sum(math_minimum), sum(math_below_minimum), sum(kannada_above_average), sum(kannada_average), sum(kannada_minimum), sum(kannada_below_minimum), (sum(math_above_average) + sum(math_average) + sum(math_minimum) + sum(math_below_minimum))
from schools_master group by year, clas;
